language: python
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: true
          python: 3.5
        - os: linux
          dist: trusty
          sudo: true
          python: 3.7-dev
before_install:
    - ./.travis/install.sh
script:
    - ./.travis/run.sh
