language: python
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: true
          python: 2.7
        - os: linux
          dist: trusty
          sudo: true
          python: 3.5
        - os: linux
          dist: trusty
          sudo: true
          python: 3.7-dev
        - os: osx
          language: objective-c
          env: PYENV_VERSION=2.7.12
        - os: osx
          language: objective-c
          env: PYENV_VERSION=3.5.2
before_install:
    - ./.travis/install.sh
install:
  - pip install tox-travis
script:
  - tox
